### ISSUE TITLE
BUG LSP crashes due to Helix missing 'window/showMessageRequest'

### ISSUE THREAD

**Issue by cat-pat** [ndonfris/fish-lsp#56]
**Describe the bug**
LSP exits a couple seconds after launching in the Helix editor

**To Reproduce**
Use the below languages.toml in global or workspace (.helix/) helix folder, change command path if needed, launch helix 

**Expected behavior**
The LSP to launch and respond to requests made by the editor.

**Please complete the following information:** 
```yaml
OS NAME: GNU/Linux
YARN VERSION: 1.22.22
NODE VERSION: v21.7.1
FISH VERSION: fish, version 3.7.1
FISH-LSP VERSION: 1.0.8
```

**Additional context**

I have the install at `/home/cat/reference_repos/typescript_fish-lsp/bin/` which includes the `fish-lsp` binary and is added to `PATH`

**Logs**
> Helix
Languages.toml
```toml
# /home/cat/reference_repos/typescript_fish-lsp/bin/fish-lsp
fish-lsp = { command = "fish-lsp", args = [
  "start",
] }

# Copied from default languages.toml
[[language]]
name = "fish"
scope = "source.fish"
injection-regex = "fish"
file-types = [ "fish" ]
shebangs = [ "fish" ]
comment-token = "#"
indent = { tab-width = 4, unit = "    " }
auto-format = true
# formatter = { command = "fish_indent" }
language-servers = [
  "fish-lsp",
]

```

Log:
```log
2024-10-01T01:27:09.006 helix_term::application [ERROR] Language Server: Method window/showMessageRequest not found in request 0
2024-10-01T01:27:09.026 helix_lsp::transport [ERROR] fish-lsp err <- "/home/cat/reference_repos/typescript_fish-lsp/node_modules/vscode-jsonrpc/lib/common/connection.js:565\n"
2024-10-01T01:27:09.027 helix_lsp::transport [ERROR] fish-lsp err <- "                        responsePromise.reject(new messages_1.ResponseError(error.code, error.message, error.data));\n"
2024-10-01T01:27:09.027 helix_lsp::transport [ERROR] fish-lsp err <- "                                               ^\n"
2024-10-01T01:27:09.027 helix_lsp::transport [ERROR] fish-lsp err <- "\n"
2024-10-01T01:27:09.027 helix_lsp::transport [ERROR] fish-lsp err <- "ResponseError: Method not found: window/showMessageRequest\n"
2024-10-01T01:27:09.027 helix_lsp::transport [ERROR] fish-lsp err <- "    at handleResponse (/home/cat/reference_repos/typescript_fish-lsp/node_modules/vscode-jsonrpc/lib/common/connection.js:565:48)\n"
2024-10-01T01:27:09.027 helix_lsp::transport [ERROR] fish-lsp err <- "    at handleMessage (/home/cat/reference_repos/typescript_fish-lsp/node_modules/vscode-jsonrpc/lib/common/connection.js:345:13)\n"
2024-10-01T01:27:09.027 helix_lsp::transport [ERROR] fish-lsp err <- "    at processMessageQueue (/home/cat/reference_repos/typescript_fish-lsp/node_modules/vscode-jsonrpc/lib/common/connection.js:362:17)\n"
2024-10-01T01:27:09.027 helix_lsp::transport [ERROR] fish-lsp err <- "    at Immediate.<anonymous> (/home/cat/reference_repos/typescript_fish-lsp/node_modules/vscode-jsonrpc/lib/common/connection.js:334:13)\n"
2024-10-01T01:27:09.027 helix_lsp::transport [ERROR] fish-lsp err <- "    at process.processImmediate (node:internal/timers:478:21) {\n"
2024-10-01T01:27:09.027 helix_lsp::transport [ERROR] fish-lsp err <- "  code: -32601,\n"
2024-10-01T01:27:09.027 helix_lsp::transport [ERROR] fish-lsp err <- "  data: undefined\n"
2024-10-01T01:27:09.027 helix_lsp::transport [ERROR] fish-lsp err <- "}\n"
2024-10-01T01:27:09.027 helix_lsp::transport [ERROR] fish-lsp err <- "\n"
2024-10-01T01:27:09.027 helix_lsp::transport [ERROR] fish-lsp err <- "Node.js v21.7.1\n"
2024-10-01T01:27:09.037 helix_lsp::transport [ERROR] fish-lsp err: <- StreamClosed
```

**Comment by ndonfris** [comment]
Hm, haven't seen an issue in helix for a while. The log messages seem to indicate that the problem is due to helix not implementing the `window/showMessage` [method of the lsp spec](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#window_showMessage). 

Testing locally, the issue seemed to be resolved by using the [fish env variable](https://github.com/ndonfris/fish-lsp#environment-variables): `$fish_lsp_show_client_popups`

```fish
# in ~/.config/fish/config.fish or somewhere else
# that your fish-shell autoloads during startup/usage

set -gx fish_lsp_show_client_popups false

```

> don't forget to source your fish config afterwards
> `source ~/.config/fish/config.fish` 

___

Here are **two** other alternative methods of providing the environment variable to your shell environment:
  <details>
  <summary><b>1.</b> set environment variable during <ins>interactive</ins> session</summary>
  
  ```fish
  >_ # note: setting to true causes error again
  >_ set -x fish_lsp_show_client_popups false; helix /tmp/foo.fish
  ```
  
  </details>
  <details>
  <summary><b>2.</b> set fish_lsp environment variables in shell <ins>function</ins></summary>
  
  ```fish
  # ~/.config/fish/config.fish
  fish_lsp_config
  ```
  ```fish
  # ~/.config/fish/functions/fish_lsp_config.fish
  function fish_lsp_config --description 'fish-lsp env --create'
      set -gx fish_lsp_show_client_popups false
  end
  ```
  
  </details>  

___

This solution stopped the server from crashing after indexing completed on my machine. If you're still experiencing issues though, feel free to use the `$fish_lsp_logfile` to provide more logs. 

___

Disabling this feature suppresses the client's ability to display **"popup"** notifications, containing messages about the status of a language-server request. Other language servers that use 'window/showMessage' include: [sumneko-lua/lua_ls](https://github.com/LuaLS/lua-language-server), [ts-server](https://github.com/microsoft/TypeScript/wiki/Standalone-Server-(tsserver)), [pyright](https://pyright-play.net/?code=AQ1kGYQxMAqALAlgZ2CghgWwA4BsBTYAEwKwHsA7FAFwCcMaC0FyB3YAY3KwsuAJ065Omk4Z%2BAIyKkmnJsXQ1GScXjwBPYJK04NdJAHMENAHQAoc6QjAMxYgAoAHgC5gEPOUYAaYBrceXjQAlC7mYHQENACudPxOwADUfpawAAoYKChIlIa2SnTAObQSnESZwDQIRCgE3JSKGHSG0VgElDTAkSjReDRoOfl00R1IbQJOZTg0SFQWdo4AjL4ARCvB5kA), etc...

  <details>
  <summary> <ins><b>SCREENSHOT</b></ins> - notification displayed once background indexing completes</summary>
  
  ![screenshot_foo_fish](https://github.com/user-attachments/assets/9e8989a0-7cdd-4342-80e0-da7658481e04)
  > (in BOTTOM RIGHT, colored BLACK w/ GREEN border)

  </details>


[fish-lsp's command provider](https://github.com/ndonfris/fish-lsp/discussions/36) also uses this feature. 

These are currently the only places where disabling `$fish_lsp_show_client_popups` will silence the notifications.   

I'd assume that this particular issue will go away as helix development continues. Keep an eye out in the future for window notification support in helix, so that you can enable the popup variable and access all features provided by this language-server.  

___

Hope this helped! If you come across your own workaround, feel free to fork and contribute to the fish-lsp :)

Thanks for the thorough bug report!

**Comment by cat-pat** [comment]
Thank you for the quick reply and additional info.

Setting `set -gx fish_lsp_show_client_popups false` did the trick, it's working perfectly as expected now.

Will close this issue since the issue is more on the Helix side

---

Relevant Issue and possible PR for anyone that may stumble upon this in the future

https://github.com/helix-editor/helix/issues/4699
https://github.com/helix-editor/helix/pull/11081
